name: scraping-spider
recipe: laravel

config:
  webroot: public
  php: '8.2'
  database: mysql:8.0
  composer_version: '2.5.4'
  cache: redis:6.0.2

services:
  appserver:
    build_as_root:
      - curl -sL https://deb.nodesource.com/setup_20.x | bash -
      - apt-get update -y
      - apt install -y nodejs
      - apt install -y libx11-6 libx11-xcb1 libxcb1 libnss3 libatk1.0-0 libatk-bridge2.0-0 libcups2 libgbm1 libasound2 libpangocairo-1.0-0 libxss1 libgtk-3-0
      - rm -rf /var/lib/apt/lists/*
      - npx puppeteer browsers install chrome
  database:
#    portforward: 32799
    creds:
      database: scraping_spider
      password: password
      user: lando
  phpmyadmin:
    type: phpmyadmin
    hosts:
      - database
  mailhog:
    type: mailhog
    ssl: true
    portforward: true
#  cache:
#    portforward: 32798

tooling:
  node:
    service: appserver
  npm:
    service: appserver

proxy:
  phpmyadmin:
    - phpmyadmin.lndo.site
  mailhog:
    - mailhog.lndo.site
