name: easy-scraper
recipe: laravel

config:
  webroot: public
  php: '8.2'
  database: mysql:8.0
  composer_version: '2.5.4'
  cache: redis:6.0.2

services:
  appserver:
    build_as_root:
      - curl -sL https://deb.nodesource.com/setup_20.x | bash -
      - apt-get install -y nodejs
  database:
    portforward: 32799
    creds:
      database: easy_scraper
      password: password
      user: lando
  phpmyadmin:
    type: phpmyadmin
    hosts:
      - database
  mailhog:
    type: mailhog
    ssl: true
    portforward: true
  cache:
    portforward: 32798

tooling:
  node:
    service: appserver
  npm:
    service: appserver

proxy:
  phpmyadmin:
    - phpmyadmin.lndo.site
  mailhog:
    - mailhog.lndo.site
